import { useState } from 'react';
import { Card } from './ui/card';
import { Input } from './ui/input';
import { Button } from './ui/button';
import { Skeleton } from './ui/skeleton';
import { Download, Search, Calendar } from 'lucide-react';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from './ui/table';
import { REPORTS } from '../lib/data/reportsData';
import { useAssignedPatients } from '../hooks/useAssignedPatients';
import { useAuth } from '../contexts/AuthContext';
import jsPDF from 'jspdf';

export function ReportsScreen() {
  const [searchQuery, setSearchQuery] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const { assignedPatientIds, isLoading } = useAssignedPatients();
  const { doctor } = useAuth();

  // Map reports to show current doctor's name
  const reportsWithCurrentDoctor = REPORTS.map(report => ({
    ...report,
    generatedBy: doctor?.name || report.generatedBy
  }));

  const filteredReports = reportsWithCurrentDoctor.filter((report) => {
    // Only show reports for assigned patients
    const isAssignedPatient = assignedPatientIds.includes(report.patientId);

    const matchesSearch =
      report.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.patientId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.generatedBy.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesDate = dateFilter
      ? report.dateGenerated.startsWith(dateFilter)
      : true;

    return isAssignedPatient && matchesSearch && matchesDate;
  });

  const handleDownload = (reportId: string) => {
    const report = reportsWithCurrentDoctor.find(r => r.id === reportId);
    if (!report) return;

    // Create new PDF document
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (2 * margin);
    let yPos = 20;

    // Header with purple background
    doc.setFillColor(168, 85, 247); // Purple color
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Care for Rare', margin, 20);

    doc.setFontSize(14);
    doc.text('Genetic Diagnostic Report', margin, 32);

    // Reset text color
    doc.setTextColor(0, 0, 0);
    yPos = 55;

    // Report Information Section
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Report Information', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const reportInfo = [
      `Report ID: ${report.id}`,
      `Patient ID: ${report.patientId}`,
      `Date Generated: ${new Date(report.dateGenerated).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`,
      `Generated By: ${report.generatedBy}`,
    ];

    reportInfo.forEach(info => {
      doc.text(info, margin, yPos);
      yPos += 7;
    });

    yPos += 10;

    // Clinical Summary Section
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Clinical Summary', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const summaryText = `This report contains comprehensive genetic analysis for patient ${report.patientId}. ` +
      `The analysis was performed using advanced AI-driven diagnostic tools to identify ` +
      `potential rare genetic diseases and candidate gene variants.`;

    const splitSummary = doc.splitTextToSize(summaryText, contentWidth);
    doc.text(splitSummary, margin, yPos);
    yPos += (splitSummary.length * 7) + 10;

    // Primary Gene Candidate Section
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Primary Gene Candidate', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const geneInfo = [
      'Gene: GATAD2B',
      'Location: Chromosome 1p36.12',
      'Function: Chromatin remodeling complex subunit',
      'Inheritance: Autosomal Dominant',
      'Mutation Type: Missense variant (de novo)',
      'Confidence Score: 92%',
    ];

    geneInfo.forEach(info => {
      doc.text(info, margin, yPos);
      yPos += 7;
    });

    yPos += 10;

    // Phenotypes Observed
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Observed Phenotypes', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const phenotypes = [
      '• Intellectual disability',
      '• Developmental delay',
      '• Hypotonia (low muscle tone)',
      '• Speech delay',
      '• Dysmorphic facial features',
    ];

    phenotypes.forEach(phenotype => {
      doc.text(phenotype, margin, yPos);
      yPos += 7;
    });

    yPos += 10;

    // Recommendations
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Clinical Recommendations', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const recommendations = [
      '• Genetic counseling for family members',
      '• Regular developmental assessments',
      '• Multidisciplinary care coordination',
      '• Consider targeted interventions based on phenotype',
    ];

    recommendations.forEach(rec => {
      doc.text(rec, margin, yPos);
      yPos += 7;
    });

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text('This report is confidential and intended for medical professionals only.', margin, footerY);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, footerY + 5);

    // Save the PDF
    doc.save(`${report.id}_${report.patientId}_Report.pdf`);
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-background">
      {/* Top Header */}
      <div className="bg-card border-b border-border px-6 py-4">
        <div className="flex items-center justify-between">
          {/* Left: Title */}
          <h1 className="text-slate-100">Report Management</h1>

          {/* Right: Filters */}
          <div className="flex items-center gap-3">
            {/* Filter by Date */}
            <div className="relative">
              <Calendar
                size={18}
                className="absolute left-3 top-1/2 transform -translate-y-1/2 text-purple-400"
              />
              <Input
                type="date"
                placeholder="Filter by Date"
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value)}
                className="pl-10 w-56 bg-[#2d1b4e] border-purple-900/20 text-slate-200"
              />
            </div>

            {/* Search Reports */}
            <div className="relative">
              <Search
                size={18}
                className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400"
              />
              <Input
                type="text"
                placeholder="Search Reports"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10 w-64 bg-[#2d1b4e] border-purple-900/20 text-slate-200 placeholder:text-slate-500"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 overflow-auto p-6">
        <Card className="bg-card border-border">
          <div className="p-6">
            <h2 className="mb-6 text-slate-100">Generated Reports</h2>

            <Table>
              <TableHeader>
                <TableRow className="border-purple-900/20 hover:bg-transparent">
                  <TableHead className="text-slate-300">Report ID</TableHead>
                  <TableHead className="text-slate-300">Patient ID</TableHead>
                  <TableHead className="text-slate-300">Date Generated</TableHead>
                  <TableHead className="text-slate-300">Generated By</TableHead>
                  <TableHead className="text-right text-slate-300">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  // Loading skeleton
                  Array.from({ length: 5 }).map((_, index) => (
                    <TableRow key={index} className="border-purple-900/20">
                      <TableCell>
                        <Skeleton className="h-4 w-24 bg-purple-900/20" />
                      </TableCell>
                      <TableCell>
                        <Skeleton className="h-4 w-20 bg-purple-900/20" />
                      </TableCell>
                      <TableCell>
                        <Skeleton className="h-4 w-28 bg-purple-900/20" />
                      </TableCell>
                      <TableCell>
                        <Skeleton className="h-4 w-32 bg-purple-900/20" />
                      </TableCell>
                      <TableCell className="text-right">
                        <Skeleton className="h-8 w-32 ml-auto bg-purple-900/20" />
                      </TableCell>
                    </TableRow>
                  ))
                ) : filteredReports.length === 0 ? (
                  <TableRow className="border-purple-900/20 hover:bg-purple-900/10">
                    <TableCell colSpan={5} className="text-center text-slate-400 py-8">
                      No reports found
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredReports.map((report) => (
                    <TableRow key={report.id} className="border-purple-900/20 hover:bg-purple-900/10">
                      <TableCell className="text-slate-100">
                        {report.id}
                      </TableCell>
                      <TableCell className="text-purple-400">
                        {report.patientId}
                      </TableCell>
                      <TableCell className="text-slate-300">
                        {new Date(report.dateGenerated).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'short',
                          day: 'numeric',
                        })}
                      </TableCell>
                      <TableCell className="text-slate-300">
                        {report.generatedBy}
                      </TableCell>
                      <TableCell className="text-right">
                        <Button
                          size="sm"
                          className="bg-purple-600 hover:bg-purple-700 gap-2"
                          onClick={() => handleDownload(report.id)}
                        >
                          <Download size={16} />
                          Download (PDF)
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </Card>
      </div>
    </div>
  );
}
